name: template
description: "Flutter Starter Template"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  amplify_auth_cognito: ^1.6.0
  amplify_authenticator: ^1.5.1
  amplify_flutter: ^1.6.0
  amplify_storage_s3: ^1.6.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.7.2
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.2
  flutter_localization: ^0.1.14
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_storage: ^2.1.1
  internet_connection_checker_plus: ^2.1.0
  intl: ^0.18.1
  json_theme: ^6.4.0
  logger: ^2.0.2+1
  salomon_bottom_bar: ^3.3.2
  sentry_flutter: ^7.13.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/png/
    - assets/images/svg/
